services:

  appointment-service-db:
    image: postgres:18.2
    container_name: appointment-service-db
    volumes:
      - appointment-service-pg18-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: 'appointment'
      POSTGRES_PASSWORD: 'appointment'
      POSTGRES_DB: 'appointment_data'
    ports:
      - "5432:5432"

volumes:
  appointment-service-pg18-data:
    driver: local
